// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import Footer from "@/Components/Footer"
import "../styles/globals.css"
import Navbar from "@/Components/Navbar"
// import Navbar from "../components/Navbar"
// import Footer from "../components/Footer"

export const metadata = {
  title: "Khandaker Mansura | Portfolio",
  description: "Junior MERN Stack Developer Portfolio",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-dark text-white">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
